### PR TITLE
[INFRA] Adding tests

### LINKED ISSUE #6: [TEST] Add automatic tests
Also update the GitHub workflow introduced by #25 
See https://r-pkgs.org/tests.html and https://r-pkgs.org/r-cmd-check.html#tests-1

For coverage, see
- https://www.rostrum.blog/2020/08/09/ghactions-pkgs/#example-r2eng-package
- https://github.com/matt-dray/r2eng/blob/master/.github/workflows/test-coverage.yaml

### PR DESCRIPTION
**Pull request by ColinFay**
This closes #6 

Funs has been moved to another file, so that they can be tested independently. 

- devtools::check()

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 28 ]

- covr::package_coverage()

bpmnVisualization Coverage: 100.00%
R/bpmnVisualization.R: 100.00%
R/funs.R: 100.00%

### CODE REVIEW

**Comment by tbouffard** [comment]
Thanks for your contribution, we are going to review it in the next days.
In the meantime, I have seen that the GitHub Actions run are failing. Can you have a look at it? If you suspect that there is an issue in the workflow definition not related to your changes, please let us know.

**Comment by ColinFay** [comment]
Sure thing. 

Yes, that's an issue with {htmlwidgets} that depends on {shiny} but doesn't actually import it, yet it still needs it in its renderer (which seems to be a bug in {htmlwidget}?). 
https://cran.r-project.org/web/packages/htmlwidgets/index.html
 
Anyway, feel like the issue was there from before my tests (package might not be working if you only had {htmlwidgets} installed), but I'll add the dep in the widget builder so that it works.

What do you prefer : 

1. Hard requirement, i.e. direct dependency
2. Checking if the package is installed with rlang::is_installed() and then adding {shiny} as Suggest

?

**Comment by tbouffard** [comment]
Thanks for the details about `htmlwidgets`.
That's strange we didn't notice it before but maybe because `shiny` was installed on the machine we used for the test 😄 

Anyway, tests are proving the issue, so let's fix this. I would prefer solution 2 because our code doesn't depend on `shiny` directly. We add `shiny` only because of the presumed bug in `htmlwidgets`.

**Comment by ColinFay** [comment]
Hey, 

I just updated the code to reflect these changes :) 

Cheers, 
Colin

**Review by tbouffard — APPROVED** [review]
Thanks a lot @ColinFay I really appreciate this contribution: it detects and fix an issue with the missing `{shiny}` dependency, it improves the documentation of the functions and the function extraction makes the code easier to read 💯 

As mentioned in https://github.com/process-analytics/bpmn-visualization-R/issues/33#issuecomment-1276355483, this PR includes additional formatting of the code, but this is perfectly acceptable as the project currently has no formatting guidelines.
This is definitely something we will have to work on soon!

**Review by csouchet — APPROVED** [review]
Thank you very much for your contribution and for your help on this part 🙏🏻 

I will be happy if you want to help us on another subject 🙂

**Comment by tbouffard** [comment]
Hi @ColinFay and thanks again for your contributions.

❓  I have one last question because I am curious 😸 . 
Apparently, you made a contribution as part of Hacktoberfest. I would like to know how you found out about our repository.
This would help us in the future to reach more potential contributors.

**Pull request merged**
